### ISSUE TITLE
how can I decypher movements in solutions?

### ISSUE THREAD

**Issue by skliarie** [Sec42/vexedsolver#1]
For example in this one, what is meaning of each char?
solution=eCdFdCeC

**Comment by Sec42** [comment]
Hi,

the point of the included script is to find the solution itself. It prints the steps in visual format once it found a solution.

As you saw, some of the included level files already include a solution. This solution is not always the best, and ignored by the script.

To answer your question anyway: each two-character pair indicates which position on the board should be moved (column first, then row), and if the first letter is upper case, it's a move left, if the second letter is uppercase it's a move right. Counting starts in the upper left corner of the level.

e.g. for the Level "Good Night" with the "solution=eCdFdCeC" line

```
##########
##########
###ba  ###
#####  ###
###    ###
###a  b###
####ab####
##########
```

decodes to:
1) move col=5,row=3 right
    (topmost a right, falls down)
2) move col=4,row=6 right
    (leftmost a right, clears all three a)
3) move col=4,row=3 right
    (topmost b right)
4) move col=5,row=3 right
    (topmost b right again, falls down and clears b)

Hope that helps.
