### ISSUE TITLE
Please restore solutions into the main tree

### ISSUE THREAD

**Issue by skliarie** [Sec42/vexedsolver#2]
The https://github.com/Sec42/vexedsolver/blob/master/Levels-Android/confusion_pack.txt have contained solutions that were deleted 15 days ago:
https://github.com/Sec42/vexedsolver/commit/a91f7899da7833ad3f5cabb9ca8bb9169591f65b

could you restore the solutions somehow please?

**Comment by Sec42** [comment]
You are mistaken. The Android levels never contained solutions. The precomputed solutions are part of the PalmOS levels which have moved to the Levels-Palm subdirectory: https://github.com/Sec42/vexedsolver/tree/master/Levels-Palm/ in this commit: https://github.com/Sec42/vexedsolver/commit/e92dc1e14f4f0b5bff706228a7eb3626ebe2b0c5
